### PR TITLE
Admin UI access control

### PR DESCRIPTION
**Pull request by loan-laux**
Signed-off-by: Loan Laux <loan@outgrow.io>

Impact: **critical**
Type: **feature**

This pull request adds a first version of the admin UI access control feature, which includes:

- An `adminUIShopIds` field added to the `Account` schema, which lists the IDs of the shops each user can administer through `reaction-admin`
- A migration which populates the `adminUIShopIds` field for older shops based on `owner` groups in the `Groups` collection
- An `adminUIShops` field added to the `Account` GraphQL schema which returns an array of shops matching the account's `adminUIShopIds`, query-able with the `viewer` query
- `grantAdminUIAccess`, `revokeAdminUIAccess` and `updateAdminUIAccess` mutations to control admin UI shop/account assignments

These were the guidelines provided by @aldeed on [this issue](https://github.com/reactioncommerce/reaction-admin/issues/93#issuecomment-598295994).

## Breaking changes
None.

## Testing
1. Create a shop with an account, confirm that this shop gets added to the account's `adminUIShopIds` array in the `Accounts` collection.
2. Use this PR on a previously-used instance of Reaction Commerce. The migration should be mandatory, and the owner accounts should get their respective shop IDs assigned in the `Accounts` collection as `adminUIShopIds` upon running it.
3. Querying an account (for example with the `viewer` query) should return a list of the shops it has admin UI access to under the `adminUIShops` field.
4. Grant admin UI access to a shop for an account with `grantAdminUIAccess`. Confirm that the shop gets pushed to `adminUIShopIds` in the account's `Accounts` object.
5. Revoke admin UI access from a shop for an account with `revokeAdminUIAccess`. Confirm that the shop gets pulled from `adminUIShopIds` in the account's `Accounts` object.
6. Bulk-update admin UI access to multiple shops for one or multiple accounts with `updateAdminUIAccess`. Confirm that the `adminUIShopIds` get updated in the accounts' `Accounts` objects.

### CODE REVIEW

**Comment by loan-laux** [comment]
@aldeed This PR contains all of the work that was done on the private repo, as well as the suggestions you provided regarding removing the `afterAccountUpdate` event handler and using a flag in the account invites instead. This is good for a review. Let me know if you find anything wrong.

**Comment by loan-laux** [comment]
@mikemurray @focusaurus — if you'd like to pick up where @aldeed left, feel free!

**Comment by focusaurus** [comment]
@loan-laux OK will set aside some time to test this out next week. Thanks!

**Review by rosshadden — CHANGES_REQUESTED** [review]
Some (probably new) conflicts have emerged.

**Comment by loan-laux** [comment]
@rosshadden Thanks! Resolved the conflicts, fixed the linting and confirmed that tests are all green.

**Review by rosshadden — APPROVED** [review]

**Comment by rosshadden** [comment]
The tests seem to be failing. Is it related to this PR or something you think had been already failing beforehand?

```
Error: Cannot find module '@reactioncommerce/api-utils/lib/configs/jest.config.cjs'
```

**Comment by loan-laux** [comment]
@rosshadden Looking at the build history on CircleCI, it looks like this issue has been recurring for quite some time. I wonder if updating `@reactioncommerce/api-utils` to the latest version would solve it.

**Comment by loan-laux** [comment]
@rosshadden Thanks for merging! Could we get a release for that?

**Pull request merged**
