### PR TITLE
Check if groupIds not empty before calling updateGroupsForAccounts

### LINKED ISSUE #27: updateGroupsForAccounts should only be called in createAccount if there are groups to add
## Issue Description
The default for customers is to not belong to a group anymore.
In `createAccount`, groups default to an empty set, which is then passed to:
`updateGroupsForAccounts` as empty array: https://github.com/reactioncommerce/api-plugin-accounts/blob/add35b0fa69dc2ab7987ef897dfab218c37659c8/src/mutations/createAccount.js#L114

In `updateGroupsForAccounts`, the Groups collection is searched for docs matching `_id: { $in: [] }` which will return no elements.
Next, as the length of matching elements is 0, an error will be thrown:
https://github.com/reactioncommerce/api-plugin-accounts/blob/add35b0fa69dc2ab7987ef897dfab218c37659c8/src/mutations/updateGroupsForAccounts.js#L46

So the implications of this are:
1. There always is one redundant search in the Groups collection.
2. Every normal customer account signup will throw an Error.

This error is only present in the latest `trunk` branch, as in 1.3 there was no `updateGroupsForAccounts` and instead `createAccount` would execute `addAccountToGroup` for each element in `groups`, therefore just executing 0 times.

## (Steps to Reproduce)
I only followed along the code and stumbled on this by accident so far and didn't actually test.

## Possible Solution
Check in `createAccount` if there are actually groups to add, and decide wether to call `updateGroupsForAccounts`.
Optionally, make `updateGroupsForAccounts` fail gracefully with just some warning if it was called with `groupIds.length < 1`.

### Versions
trunk

Introduced here: https://github.com/reactioncommerce/api-plugin-accounts/commit/7c993f03753aa6a88bb5270c953bd2e151797ecb#diff-8da12d48810df3c6da9a60f2945ee716R116

### PR DESCRIPTION
**Pull request by loan-laux**
Resolves #27
Impact: **major**
Type: **bugfix**

## Issue
`updateGroupsForAccounts` can throw an error if no groups are provided, and in `createAccount`, the mutation is called regardless of whether there are groups to add or not.

## Solution
Check if there are groups to add to the account in `createAccount` before calling `updateGroupsForAccounts`. This will prevent the mutation from being called when it isn't needed. Also check if `groupIds` were passed before throwing an error about groups not being found.

## Breaking changes
None.

## Testing
1. Create a customer account, expect no errors.
2. Create an admin account from an invitation, expect no errors. 
3. Check that the relevant groups were added to the admin account in the `Accounts` MongoDB collection.

### CODE REVIEW

**Comment by loan-laux** [comment]
This is still not passing CI even though I merged in the latest trunk. Any ideas?

**Comment by mikemurray** [comment]
@loan-laux It looks like theres an issue with a dependency, which may be caused by the ci cache. I've updated the cache keys in the CI config here: https://github.com/reactioncommerce/api-plugin-accounts/pull/30. 

I don't know if that will help, but it shouldn't hurt.


the error:
```
ENOENT: no such file or directory, open '/root/project/node_modules/npm/node_modules/es6-promise/package.json' 
```

**Comment by mikemurray** [comment]
@loan-laux Try merging trunk into your branch now to see if tests pass.

**Comment by loan-laux** [comment]
@mikemurray Done! They now pass on my local machine, so hopefully they'll do too on the CI.

**Review by mikemurray — APPROVED** [review]
👍

**Pull request merged**
