### PR TITLE
fix: use userId directly when emitting events

### LINKED ISSUE #33: user.id is undefined in updateAccountGroup
## Issue Description
When a group is created(every time you create a shop or directly from graphQL), the console always displays this error 
`Error in "afterAccountGroupCreate" consumer TypeError: Cannot read property '_id' of null`

## Steps to Reproduce

1. Start a new reaction project
2. Create first shop which under-hood creates global groups
3. See the logs from the API

or you can use the mutation updateAccountGroup directly

## Possible Solution

Get  `userId`  from the context [here](https://github.com/reactioncommerce/api-plugin-accounts/blob/31be5b52ff2aca4f4039b4aa5c4d9719ff97f3c2/src/mutations/updateAccountGroup.js#L25)  instead of `user` , and replace it in the [event](https://github.com/reactioncommerce/api-plugin-accounts/blob/31be5b52ff2aca4f4039b4aa5c4d9719ff97f3c2/src/mutations/updateAccountGroup.js#L64) 

### Versions
1.4.4

### PR DESCRIPTION
**Pull request by Manizuca**
Signed-off-by: Matias Zuniga <matias.nicolas.zc@gmail.com>

Resolves #33
Impact: **minor**
Type: **bugfix**

## Issue
removeAccountGroup and updateAccountGroup mutations are trying to get `_id ` from the user object, that can be null.

## Solution
As suggested on the issue, use userId directly.

### CODE REVIEW

**Comment by loan-laux** [comment]
Can someone retry the build step on this? It's a small PR that's still relevant today. Would be great to merge it.

**Comment by Akarshit** [comment]
For some reason, I can't run the CircleCI stuff from repos other than reactioncommerce. I will try to pull this one in and create a new PR.

**Review by Akarshit — APPROVED** [review]

**Comment by Akarshit** [comment]
@spencern Is it possible to disable checks for external PRs. They are being flagged as "unauthorized" since the contributor is not a member of the organization.
The other way to bypass this was to allow passing of secrets to all builds which is definitely not worth doing.

**Comment by spencern** [comment]
I'm looking into this, I think we may need to adjust our circleci config a bit.

**Comment by spencern** [comment]
This should be resolved by https://github.com/reactioncommerce/api-plugin-accounts/pull/57 

It's possible there are other plugins that have this same error in the circleci config as it will only show up when a non-member PRs a change.

**Comment by Akarshit** [comment]
Thanks @Manizuca

**Pull request merged**
